import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/layout/Footer";
import Header from "../components/layout/Header";
import { SessionProvider } from "next-auth/react";
import { auth } from "../../lib/auth";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <div className="flex min-h-screen w-full items-center flex-col space-y-6">
            <Header />
            <div className="w-full max-w-6xl space-y-6 flex-grow">
              {children}
              <Toaster richColors />
            </div>
            <Footer />
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
